#!/usr/bin/env python3
"""Build the eight owned X4 providers using the pinned shared builder and SDK."""
import argparse
import importlib.util
import json
from pathlib import Path
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
PACKAGES = ('x4pro_i2c', 'x4pro_panel', 'x4pro_gt911', 'x4pro_buttons',
            'x4pro_frontlight', 'x4pro_battery', 'x4pro_rtc', 'x4pro_sd')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--runtime', type=Path, required=True, help='directory generated by prepare_runtime.py')
    parser.add_argument('--source', choices=PACKAGES)
    args = parser.parse_args()
    runtime = args.runtime.resolve()
    lock = json.loads((ROOT / 'migration-source.json').read_text())
    origin = json.loads((runtime / 'build-origin.json').read_text())
    if origin['runtime'] != lock['upstream']:
        raise ValueError('Composed runtime provenance does not match source lock')
    sys.path.insert(0, str(runtime / 'scripts'))
    spec = importlib.util.spec_from_file_location('shared_provider_builder', runtime / 'scripts/build_x4pro_drivers.py')
    builder = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(builder)
    builder.ROOT = runtime
    for name in ([args.source] if args.source else PACKAGES):
        builder.build_one(name)


if __name__ == '__main__':
    main()
